
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rityzkqiuxaohdrmproh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdHl6a3FpdXhhb2hkcm1wcm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTA4OTIsImV4cCI6MjA2NDk2Njg5Mn0.0FN2vF6BDT_c3izEMq8QfXCToXUBmzhoCtGdrKChI80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
